### ISSUE TITLE
Update `README.md`

### ISSUE THREAD

**Issue by alcpereira** [alcpereira/100hunters#14]
## Description
The `README.md` is the entry point of every project. It should be nice to read and contain links to other documentation (like `CONTRIBUTING.md` or the `docs/`).

Find some examples on Github of `README.md` and use them as inspiration.

## ACs
- Update `README.md`

**Comment by weller7** [comment]
Hello I'd like to take this one. I've been looking around for readme examples and found these. Do you think they're good to use them as inspiration for the project?

https://github.com/alec-chernicki/portfolio-template

https://github.com/ivanperez-keera/Yampa#readme

https://github.com/amitmerchant1990/electron-markdownify#readme
