### ISSUE TITLE
Commit linting

### ISSUE THREAD

**Issue by alcpereira** [alcpereira/100hunters#8]
## Description
We should try to enforce good commit messages by using [commitlint](https://commitlint.js.org/) with [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) convention.

The easiest way to setup would be by also installing [Husky](https://typicode.github.io/husky/).

Read the docs, try locally, then submit a PR.

## ACs
- Automated commit linting via `commitlint` and `husky`
- Add documentation in `docs/commit-message` and in `CONTRIBUTING.md` regarding the commit convention

**Comment by JoeDravarol** [comment]
I will work on this.
